/*

	PROJECT:		m0d_s0beit_sa
	LICENSE:		See LICENSE in the top level directory
	COPYRIGHT:		Copyright 2007, 2008, 2009, 2010 we_sux

	m0d_s0beit_sa is available from http://code.google.com/p/m0d-s0beit-sa/

	m0d_s0beit_sa is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	m0d_s0beit_sa is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with m0d_s0beit_sa.  If not, see <http://www.gnu.org/licenses/>.

*/


#ifndef __CHEAT_WEAPON
#define __CHEAT_WEAPON


/**
 * Contains the weapon types/models
 */
enum eWeaponType
{
	WEAPONTYPE_UNARMED=0,
	WEAPONTYPE_BRASSKNUCKLE, 
	WEAPONTYPE_GOLFCLUB,
	WEAPONTYPE_NIGHTSTICK,
	WEAPONTYPE_KNIFE,
	WEAPONTYPE_BASEBALLBAT,
	WEAPONTYPE_SHOVEL,
	WEAPONTYPE_POOL_CUE,
	WEAPONTYPE_KATANA,
	WEAPONTYPE_CHAINSAW,
	
	// gifts
	WEAPONTYPE_DILDO1, // 10
	WEAPONTYPE_DILDO2,
	WEAPONTYPE_VIBE1,
	WEAPONTYPE_VIBE2,
	WEAPONTYPE_FLOWERS,
	WEAPONTYPE_CANE,

	WEAPONTYPE_GRENADE,
	WEAPONTYPE_TEARGAS,
	WEAPONTYPE_MOLOTOV,
	WEAPONTYPE_ROCKET,
	WEAPONTYPE_ROCKET_HS, // 20
	WEAPONTYPE_FREEFALL_BOMB,

	// FIRST SKILL WEAPON
	WEAPONTYPE_PISTOL,			// handguns
	WEAPONTYPE_PISTOL_SILENCED,
	WEAPONTYPE_DESERT_EAGLE,
	WEAPONTYPE_SHOTGUN,			// shotguns
	WEAPONTYPE_SAWNOFF_SHOTGUN,	// one handed
	WEAPONTYPE_SPAS12_SHOTGUN,
	WEAPONTYPE_MICRO_UZI,		// submachine guns
	WEAPONTYPE_MP5,
	WEAPONTYPE_AK47, // 30  	// machine guns 
	WEAPONTYPE_M4,			
	WEAPONTYPE_TEC9,			// this uses stat from the micro_uzi
	// END SKILL WEAPONS
	
	WEAPONTYPE_COUNTRYRIFLE,	// rifles
	WEAPONTYPE_SNIPERRIFLE,	
	WEAPONTYPE_ROCKETLAUNCHER,	// specials
	WEAPONTYPE_ROCKETLAUNCHER_HS,
	WEAPONTYPE_FLAMETHROWER,
	WEAPONTYPE_MINIGUN,
	WEAPONTYPE_REMOTE_SATCHEL_CHARGE,
	WEAPONTYPE_DETONATOR, // 40	// plastic explosive
	WEAPONTYPE_SPRAYCAN,
	WEAPONTYPE_EXTINGUISHER,
	WEAPONTYPE_CAMERA,
	WEAPONTYPE_NIGHTVISION,
	WEAPONTYPE_INFRARED,
	WEAPONTYPE_PARACHUTE,
	WEAPONTYPE_LAST_WEAPONTYPE,

	WEAPONTYPE_ARMOUR,
	// these are possible ways to die
	WEAPONTYPE_RAMMEDBYCAR,
	WEAPONTYPE_RUNOVERBYCAR, // 50
	WEAPONTYPE_EXPLOSION,
	WEAPONTYPE_UZI_DRIVEBY,
	WEAPONTYPE_DROWNING,
	WEAPONTYPE_FALL,
	WEAPONTYPE_UNIDENTIFIED,	// Used for damage being done
	WEAPONTYPE_ANYMELEE,
	WEAPONTYPE_ANYWEAPON,
	WEAPONTYPE_FLARE,

    // Added by us
    WEAPONTYPE_TANK_GRENADE,
};

// VERY MUCH VC, NEEDS TO BE UPDATED
enum eWeaponModel
{
	WEAPONMODEL_CELLPHONE=258,
	WEAPONMODEL_BRASSKNUCKLE,
	WEAPONMODEL_SCREWDRIVER,
	WEAPONMODEL_GOLFCLUB,
	WEAPONMODEL_NITESTICK,
	WEAPONMODEL_KNIFECUR,
	WEAPONMODEL_BASEBALL_BAT,
	WEAPONMODEL_HAMMER,
	WEAPONMODEL_CLEAVER,
	WEAPONMODEL_MACHETE,
	WEAPONMODEL_KATANA,
	WEAPONMODEL_CHAINSAW,
	WEAPONMODEL_GRENADE,
	WEAPONMODEL_TEARGAS,
	WEAPONMODEL_MOLOTOV,
	WEAPONMODEL_MISSILE,
	WEAPONMODEL_COLT45,
	WEAPONMODEL_PYTHON,
	WEAPONMODEL_RUGER,
	WEAPONMODEL_CHROMEGUN,
	WEAPONMODEL_SHOTGSPA,
	WEAPONMODEL_BUDDYSHOT,
	WEAPONMODEL_M4,
	WEAPONMODEL_TEC9,
	WEAPONMODEL_UZI,
	WEAPONMODEL_INGRAMSL,
	WEAPONMODEL_MP5LNG,
	WEAPONMODEL_SNIPER,
	WEAPONMODEL_LASER,
	WEAPONMODEL_ROCKETLA,
	WEAPONMODEL_FLAME,
	WEAPONMODEL_M60,
	WEAPONMODEL_MINIGUN,
	WEAPONMODEL_BOMB,
	WEAPONMODEL_CAMERA,
	WEAPONMODEL_FINGERS,
	WEAPONMODEL_MINIGUN2
};


#endif